FROM maven AS servlet
COPY pom.xml /tmp/
COPY src /tmp/src/
WORKDIR /tmp/
RUN mvn clean package

FROM tomcat:9.0
COPY --from=servlets /tmp/target/servlets*.war $CATALINA_HOME/webapps/servlets.war
COPY server.xml $CATALINA_HOME/conf/server.xml